### ISSUE TITLE
Contributor Guideline

### ISSUE THREAD

**Issue by mainanick** [geofmureithi/loopy#2]
Would love to contribute on this great tool.Any guidelines?

**Comment by geofmureithi-zz** [comment]
Note Coding standard -> [Standard Js](https://standardjs.com)

## Contributing
1. Create your feature branch: `git checkout -b my-new-feature`
2. Commit your changes: `git commit -m 'Add some feature'`
3. Push to the branch: `git push origin my-new-feature`
4. Submit a pull request :D
