### ISSUE TITLE
.env.example

### ISSUE THREAD

**Issue by 0x8801** [geofmureithi/loopy#3]
Awesome tool :D 

What/where are the environment variables?

**Comment by geofmureithi-zz** [comment]
Should be fixed by:
https://github.com/geofmureithi/loopy/commit/b5e22e7affcb13897fd077cb3a67201e6b32fa46
https://github.com/geofmureithi/loopy/commit/1e889c906657849853b5783af9faaab760bb9b01

**Comment by 0x8801** [comment]
👍
